disabled_rules:
  - closure_parameter_position
  - colon
  - comma
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - reduce_boolean
  - todo
  - type_body_length
  - type_name
included:
  - Classes

switch_case_alignment:
  indented_cases: true

trailing_comma:
  mandatory_comma: true

line_length:
  warning: 140
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_function_declarations: true
  ignores_urls: true
