fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  lane :new_minor do 
    rlz(bump_type: "minor")
  end

  lane :rlz do |options|
    skip_docs()
    cocoapods(
      try_repo_update_on_error: true,
      use_bundle_exec: true,
    )

    swiftlint(
      mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
      path: "./Sources",       # Specify path to lint (optional)
      executable: "./Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
      strict: true,
      raise_if_swiftlint_error: true,      # Allow fastlane to raise an error if swiftlint fails
      ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )

    run_tests(
      project: "./Pods/Pods.xcodeproj",
      scheme: "MapGL-Unit-Tests",
      sdk: "iphonesimulator",
    )
    
    version = options[:version]
    if version.to_s.empty?
      bump_type = options[:bump_type]
      if bump_type.to_s.empty?
        version_bump_podspec(bump_type: "patch")
      else
        version_bump_podspec(bump_type: bump_type)
      end
      version = lane_context[SharedValues::PODSPEC_VERSION_NUMBER]
    else
      version_bump_podspec(version_number: version)  
    end
    
    git_commit(
      message: "Bump up version to #{version}",
      path: ["./*"]
    )
    add_git_tag(
      tag: "v#{version}"
    )
    push_to_git_remote
    pod_push(allow_warnings: true, use_bundle_exec: true)
  end

end

